version: '3.4'

services:
  observercronmanager:
    image: observercronmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      CRON_STORE: /etc/cron.d/
      NODE_BIN: /usr/bin/node
      ENV_DATABASE: "sqlite"
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
